version: '3.5'

services:
  postgres:
    image: postgres:14.5
    container_name: kc_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev