server:
  port: 8081

logging:
  level:
    org.keycloak: trace


keycloak:
  realm: my-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: client-creds-receiver
  bearer-only: true
  use-resource-role-mappings: true
  public-client: true
  credentials:
    secret: NUB8swqqvvJC9fabCGRpCTRmMJNpVOmI
#  security-constraints:
#    - auth-roles:
#        - access
#    - security-collections:
#        - name: my-collection
#          patterns:
#            - /**
#      auth-roles:
#        - access
#  cors: false
#  cors-allowed-methods: GET, POST, PUT, DELETE